CREATE TABLE recipes_users (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  user_name TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  password TEXT NOT NULL,
  date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
  date_modified TIMESTAMPTZ
);

ALTER TABLE recipes_table
  ADD COLUMN
    author_id INTEGER REFERENCES recipes_users(id)
    ON DELETE SET NULL;
