CREATE TABLE recipes_feedbacks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    text TEXT NOT NULL,
    likes boolean,
    dislike boolean,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    recipe_id INTEGER
        REFERENCES recipes_table(id) ON DELETE CASCADE NOT NULL,
    user_id INTEGER
        REFERENCES recipes_users(id) ON DELETE CASCADE NOT NULL
);
